import hashlib
import json
import os
import shutil
import struct
import subprocess
import sys
import tempfile
import unittest
import xml.etree.ElementTree as ET
import zipfile
from collections import defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
BUILD_MODELS = ROOT / "scripts" / "build-models.sh"
BUILD_P1S = ROOT / "scripts" / "build-p1s.sh"
BUILD_RENDER = ROOT / "scripts" / "build-render.sh"
BUILD_ALL = ROOT / "scripts" / "build-all.sh"
VALIDATOR = ROOT / "scripts" / "validate_release.py"
P1S_FIXTURE = ROOT / "dist" / "wardrobe_rail_bracket_P1S_0.4_PLA_2x.gcode.3mf"

EXPECTED = {
    "wardrobe_rail_bracket_main.stl": ((63.5, 75.0, 50.0), 1),
    "wardrobe_rail_bracket_cap.stl": ((63.5, 24.0, 15.7), 1),
    "wardrobe_rail_bracket_main.3mf": ((63.5, 75.0, 50.0), 1),
    "wardrobe_rail_bracket_cap.3mf": ((63.5, 24.0, 15.7), 1),
    "wardrobe_rail_bracket_complete.3mf": ((133.5, 75.0, 50.0), 2),
}

RELEASE_FILENAMES = set(EXPECTED)


class RenderBuildTests(unittest.TestCase):
    def test_missing_xvfb_preserves_render_destination(self):
        self.assertTrue(BUILD_RENDER.is_file(), "scripts/build-render.sh is missing")

        with tempfile.TemporaryDirectory() as temporary_directory:
            temporary_path = Path(temporary_directory)
            output = temporary_path / "render.png"
            sentinel = b"known-good render\x00\xff"
            output.write_bytes(sentinel)
            environment = os.environ | {
                "XVFB_RUN_BIN": "/definitely/missing/xvfb-run",
            }

            result = subprocess.run(
                [str(BUILD_RENDER), "--output", str(output)],
                text=True,
                capture_output=True,
                env=environment,
            )

            self.assertNotEqual(result.returncode, 0)
            self.assertIn("Xvfb", result.stderr)
            self.assertIn(
                "https://packages.ubuntu.com/search?keywords=xvfb",
                result.stderr,
            )
            self.assertEqual(output.read_bytes(), sentinel)


class AggregateBuildTests(unittest.TestCase):
    def make_executable(self, path: Path, contents: str):
        path.write_text(contents, encoding="utf-8")
        path.chmod(0o755)

    def test_invalid_explicit_xvfb_skips_render_even_when_path_has_xvfb(self):
        with tempfile.TemporaryDirectory() as temporary_directory:
            temporary_path = Path(temporary_directory)
            scripts = temporary_path / "scripts"
            scripts.mkdir()
            build_all = scripts / "build-all.sh"
            shutil.copy2(BUILD_ALL, build_all)
            build_all.chmod(0o755)

            events = temporary_path / "events.txt"
            image = temporary_path / "bracket-render.png"
            sentinel = b"existing render\x00\xff"
            image.write_bytes(sentinel)
            fake_bin = temporary_path / "bin"
            fake_bin.mkdir()
            self.make_executable(
                scripts / "build-models.sh",
                "#!/bin/sh\nprintf '%s\\n' models >> \"$EVENT_LOG\"\n",
            )
            self.make_executable(
                scripts / "build-p1s.sh",
                "#!/bin/sh\nprintf '%s\\n' p1s >> \"$EVENT_LOG\"\n",
            )
            self.make_executable(
                scripts / "build-render.sh",
                "#!/bin/sh\n"
                "printf '%s\\n' render >> \"$EVENT_LOG\"\n"
                ">\"$IMAGE_PATH\"\n",
            )
            self.make_executable(
                fake_bin / "xvfb-run",
                "#!/bin/sh\nexit 91\n",
            )

            environment = os.environ | {
                "EVENT_LOG": str(events),
                "IMAGE_PATH": str(image),
                "PATH": f"{fake_bin}:{os.environ['PATH']}",
                "XVFB_RUN_BIN": "/definitely/missing/xvfb-run",
            }
            result = subprocess.run(
                [str(build_all)],
                text=True,
                capture_output=True,
                env=environment,
            )

            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertEqual(
                events.read_text(encoding="utf-8").splitlines(), ["models", "p1s"]
            )
            self.assertEqual(
                result.stderr,
                "warning: Xvfb not found; keeping existing render\n",
            )
            self.assertEqual(image.read_bytes(), sentinel)


def binary_stl_triangles(path: Path):
    data = path.read_bytes()
    if len(data) < 84:
        raise AssertionError(f"STL is too small: {len(data)} bytes")

    triangle_count = struct.unpack_from("<I", data, 80)[0]
    if 84 + triangle_count * 50 != len(data):
        raise AssertionError("Expected a binary STL generated by OpenSCAD")

    return [
        [
            struct.unpack_from("<fff", data, 84 + triangle * 50 + 12 + vertex * 12)
            for vertex in range(3)
        ]
        for triangle in range(triangle_count)
    ]


def model_triangles_from_3mf(path: Path):
    with zipfile.ZipFile(path) as archive:
        model = ET.fromstring(archive.read("3D/3dmodel.model"))

    namespace = "{http://schemas.microsoft.com/3dmanufacturing/core/2015/02}"
    vertices = [
        tuple(float(vertex.attrib[axis]) for axis in ("x", "y", "z"))
        for vertex in model.findall(f".//{namespace}vertex")
    ]
    return [
        [
            vertices[int(triangle.attrib[corner])]
            for corner in ("v1", "v2", "v3")
        ]
        for triangle in model.findall(f".//{namespace}triangle")
    ]


def envelope_and_components(triangles):
    coordinates = list(zip(*(vertex for triangle in triangles for vertex in triangle)))
    lower = tuple(min(axis) for axis in coordinates)
    upper = tuple(max(axis) for axis in coordinates)

    edge_triangles = defaultdict(list)
    for index, triangle in enumerate(triangles):
        for start, end in ((0, 1), (1, 2), (2, 0)):
            edge_triangles[tuple(sorted((triangle[start], triangle[end])))].append(index)

    neighbours = defaultdict(set)
    for adjacent_triangles in edge_triangles.values():
        for triangle in adjacent_triangles:
            neighbours[triangle].update(
                other for other in adjacent_triangles if other != triangle
            )

    unseen = set(range(len(triangles)))
    components = 0
    while unseen:
        components += 1
        pending = [unseen.pop()]
        while pending:
            adjacent = neighbours[pending.pop()] & unseen
            unseen.difference_update(adjacent)
            pending.extend(adjacent)

    return tuple(round(high - low, 1) for low, high in zip(lower, upper)), components, lower


class ReleaseModelBuildTests(unittest.TestCase):
    def test_repository_has_no_obsolete_root_model_exports(self):
        for filename in ("wardrobe_rail_bracket.3mf", "wardrobe_rail_bracket.stl"):
            with self.subTest(filename=filename):
                self.assertFalse(
                    (ROOT / filename).exists(),
                    f"obsolete root model export found: {filename}",
                )

    def run_builder(self, output_directory: Path, environment=None):
        self.assertTrue(BUILD_MODELS.is_file(), "scripts/build-models.sh is missing")
        return subprocess.run(
            [str(BUILD_MODELS), "--output-dir", str(output_directory)],
            text=True,
            capture_output=True,
            env=environment,
        )

    def test_builds_portable_models_with_expected_print_envelopes(self):
        with tempfile.TemporaryDirectory() as temporary_directory:
            output_directory = Path(temporary_directory)
            result = self.run_builder(output_directory)

            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertEqual(
                {path.name for path in output_directory.iterdir()}, RELEASE_FILENAMES
            )

            for filename, (expected_size, expected_components) in EXPECTED.items():
                with self.subTest(filename=filename):
                    output = output_directory / filename
                    triangles = (
                        binary_stl_triangles(output)
                        if output.suffix == ".stl"
                        else model_triangles_from_3mf(output)
                    )
                    size, components, lower = envelope_and_components(triangles)
                    self.assertEqual(size, expected_size)
                    self.assertEqual(components, expected_components)
                    self.assertGreaterEqual(lower[2], 0.0)

            for filename in (
                "wardrobe_rail_bracket_main.3mf",
                "wardrobe_rail_bracket_cap.3mf",
                "wardrobe_rail_bracket_complete.3mf",
            ):
                with self.subTest(filename=filename, contract="neutral archive"):
                    self.assert_clean_3mf(output_directory / filename)

    def test_complete_model_is_neutral_two_volume_print_layout(self):
        with tempfile.TemporaryDirectory() as temporary_directory:
            output_directory = Path(temporary_directory)
            result = self.run_builder(output_directory)

            self.assertEqual(result.returncode, 0, result.stderr)
            complete = output_directory / "wardrobe_rail_bracket_complete.3mf"
            triangles = model_triangles_from_3mf(complete)
            _, components, lower = envelope_and_components(triangles)
            self.assertEqual(components, 2)
            self.assertGreaterEqual(lower[2], 0.0)

            self.assert_clean_3mf(complete)

    def test_builds_with_no_display_server(self):
        openscad = shutil.which("openscad")
        self.assertIsNotNone(openscad, "OpenSCAD CLI is not installed")

        with tempfile.TemporaryDirectory() as temporary_directory:
            temporary_path = Path(temporary_directory)
            wrapper = temporary_path / "headless-openscad"
            wrapper.write_text(
                "#!/usr/bin/env sh\n"
                "[ -z \"${DISPLAY-}\" ] || exit 61\n"
                "[ -z \"${WAYLAND_DISPLAY-}\" ] || exit 62\n"
                "[ \"${QT_QPA_PLATFORM-}\" = offscreen ] || exit 63\n"
                f"exec {openscad} \"$@\"\n",
                encoding="utf-8",
            )
            wrapper.chmod(0o755)
            environment = os.environ | {"OPENSCAD_BIN": str(wrapper)}
            environment.pop("DISPLAY", None)
            environment.pop("WAYLAND_DISPLAY", None)
            environment.pop("QT_QPA_PLATFORM", None)

            result = self.run_builder(temporary_path / "models", environment)

            self.assertEqual(result.returncode, 0, result.stderr)

    def test_missing_openscad_leaves_output_directory_unchanged(self):
        with tempfile.TemporaryDirectory() as temporary_directory:
            output_directory = Path(temporary_directory)
            sentinel = output_directory / "keep.txt"
            sentinel.write_text("do not touch", encoding="utf-8")
            environment = os.environ | {"OPENSCAD_BIN": "/definitely/missing/openscad"}
            result = self.run_builder(output_directory, environment)

            self.assertNotEqual(result.returncode, 0)
            self.assertIn("OpenSCAD", result.stderr)
            self.assertIn("https://openscad.org/downloads.html", result.stderr)
            self.assertEqual(sentinel.read_text(encoding="utf-8"), "do not touch")
            self.assertFalse(RELEASE_FILENAMES & {path.name for path in output_directory.iterdir()})

    def test_missing_python3_leaves_all_existing_models_unchanged(self):
        with tempfile.TemporaryDirectory() as temporary_directory:
            output_directory = Path(temporary_directory)
            expected = {}
            for index, filename in enumerate(sorted(RELEASE_FILENAMES)):
                payload = f"existing model {index}".encode() + b"\x00\xff"
                (output_directory / filename).write_bytes(payload)
                expected[filename] = payload
            environment = os.environ | {
                "PYTHON_BIN": "/definitely/missing/python3",
                "OPENSCAD_BIN": "/definitely/missing/openscad",
            }

            result = self.run_builder(output_directory, environment)

            self.assertNotEqual(result.returncode, 0)
            self.assertIn("Python 3", result.stderr)
            self.assertIn("https://www.python.org/downloads/", result.stderr)
            self.assertEqual(
                {path.name: path.read_bytes() for path in output_directory.iterdir()},
                expected,
            )

    def test_nominal_openscad_success_with_malformed_model_preserves_whole_set(self):
        with tempfile.TemporaryDirectory() as temporary_directory:
            temporary_path = Path(temporary_directory)
            output_directory = temporary_path / "models"
            output_directory.mkdir()
            expected = {}
            for index, filename in enumerate(sorted(RELEASE_FILENAMES)):
                payload = f"existing model {index}".encode() + b"\x00\xff"
                (output_directory / filename).write_bytes(payload)
                expected[filename] = payload

            openscad = temporary_path / "openscad"
            openscad.write_text(
                "#!/usr/bin/env python3\n"
                "import os, pathlib, shutil, sys\n"
                "args = sys.argv[1:]\n"
                "output = pathlib.Path(args[args.index('-o') + 1])\n"
                "source = pathlib.Path(os.environ['MODEL_FIXTURES']) / output.name\n"
                "shutil.copy2(source, output)\n"
                "if output.name == 'wardrobe_rail_bracket_main.stl':\n"
                "    output.write_bytes(b'nonempty but malformed STL')\n",
                encoding="utf-8",
            )
            openscad.chmod(0o755)
            environment = os.environ | {
                "MODEL_FIXTURES": str(ROOT / "dist" / "models"),
                "OPENSCAD_BIN": str(openscad),
                "PYTHON_BIN": sys.executable,
            }

            result = self.run_builder(output_directory, environment)

            self.assertNotEqual(result.returncode, 0)
            self.assertIn("STL", result.stderr)
            self.assertEqual(
                {path.name: path.read_bytes() for path in output_directory.iterdir()},
                expected,
            )

    def test_nominal_openscad_success_with_incomplete_model_preserves_whole_set(self):
        with tempfile.TemporaryDirectory() as temporary_directory:
            temporary_path = Path(temporary_directory)
            output_directory = temporary_path / "models"
            output_directory.mkdir()
            expected = {}
            for index, filename in enumerate(sorted(RELEASE_FILENAMES)):
                payload = f"existing model {index}".encode() + b"\x00\xff"
                (output_directory / filename).write_bytes(payload)
                expected[filename] = payload

            openscad = temporary_path / "openscad"
            openscad.write_text(
                "#!/usr/bin/env python3\n"
                "import os, pathlib, shutil, sys\n"
                "args = sys.argv[1:]\n"
                "output = pathlib.Path(args[args.index('-o') + 1])\n"
                "if output.name != 'wardrobe_rail_bracket_complete.3mf':\n"
                "    source = pathlib.Path(os.environ['MODEL_FIXTURES']) / output.name\n"
                "    shutil.copy2(source, output)\n",
                encoding="utf-8",
            )
            openscad.chmod(0o755)
            environment = os.environ | {
                "MODEL_FIXTURES": str(ROOT / "dist" / "models"),
                "OPENSCAD_BIN": str(openscad),
                "PYTHON_BIN": sys.executable,
            }

            result = self.run_builder(output_directory, environment)

            self.assertNotEqual(result.returncode, 0)
            self.assertIn("nonempty", result.stderr)
            self.assertEqual(
                {path.name: path.read_bytes() for path in output_directory.iterdir()},
                expected,
            )

    def assert_clean_3mf(self, output: Path):
        with zipfile.ZipFile(output) as archive:
            names = archive.namelist()
        self.assertFalse(any(name.endswith(".gcode") for name in names))
        self.assertFalse(
            {
                "Metadata/project_settings.config",
                "Metadata/model_settings.config",
                "Metadata/slice_info.config",
            }
            & set(names)
        )


class P1SBuildTests(unittest.TestCase):
    def make_executable(self, path: Path, contents: str):
        path.write_text(contents, encoding="utf-8")
        path.chmod(0o755)

    def rewrite_archive(self, path: Path, replacements):
        temporary = path.with_name(f".{path.name}.rewrite")
        with zipfile.ZipFile(path) as source, zipfile.ZipFile(
            temporary, "w", compression=zipfile.ZIP_DEFLATED
        ) as destination:
            for member in source.namelist():
                destination.writestr(
                    member, replacements.get(member, source.read(member))
                )
        temporary.replace(path)

    def make_fixture_orca(self, path: Path):
        self.make_executable(
            path,
            "#!/usr/bin/env python3\n"
            "import json, os, pathlib, shutil, sys\n"
            "args = sys.argv[1:]\n"
            "if args == ['--help']:\n"
            "    print('OrcaSlicer-2.4.2:')\n"
            "    raise SystemExit(0)\n"
            "output_directory = pathlib.Path(args[args.index('--outputdir') + 1])\n"
            "archive_name = args[args.index('--export-3mf') + 1]\n"
            "shutil.copy2(\n"
            "    os.environ['INVALID_P1S_FIXTURE'], output_directory / archive_name\n"
            ")\n"
            "(output_directory / 'result.json').write_text(\n"
            "    json.dumps({'return_code': 0}), encoding='utf-8'\n"
            ")\n",
        )

    def run_builder(self, output: Path, environment=None):
        self.assertTrue(BUILD_P1S.is_file(), "scripts/build-p1s.sh is missing")
        return subprocess.run(
            [str(BUILD_P1S), "--output", str(output)],
            text=True,
            capture_output=True,
            env=environment,
        )

    def test_committed_profiles_are_flattened_official_presets_with_overlay(self):
        profile_directory = ROOT / "profiles" / "orca"
        machine = json.loads(
            (profile_directory / "p1s-0.4-machine.json").read_text(encoding="utf-8")
        )
        filament = json.loads(
            (profile_directory / "pla-basic.json").read_text(encoding="utf-8")
        )
        process = json.loads(
            (profile_directory / "bracket-strength.json").read_text(
                encoding="utf-8"
            )
        )

        for profile in (machine, filament, process):
            self.assertNotIn("inherits", profile)

        self.assertEqual(machine["name"], "Bambu Lab P1S 0.4 nozzle")
        self.assertEqual(machine["printer_model"], "Bambu Lab P1S")
        self.assertEqual(machine["printer_variant"], "0.4")
        self.assertEqual(filament["name"], "Bambu PLA Basic @BBL X1C")
        self.assertEqual(filament["filament_vendor"], ["Bambu Lab"])
        self.assertEqual(process["name"], "0.20mm Standard @BBL X1C")

        expected_overlay = {
            "layer_height": "0.2",
            "wall_loops": "5",
            "top_shell_layers": "6",
            "bottom_shell_layers": "6",
            "sparse_infill_density": "40%",
            "sparse_infill_pattern": "gyroid",
            "enable_support": "0",
            "brim_type": "outer_only",
            "brim_width": "5",
            "brim_object_gap": "0.1",
            "print_sequence": "by layer",
            "outer_wall_speed": "120",
            "inner_wall_speed": "200",
            "sparse_infill_speed": "200",
        }
        self.assertEqual(
            {key: process[key] for key in expected_overlay}, expected_overlay
        )

    def test_missing_orcaslicer_preserves_destination(self):
        with tempfile.TemporaryDirectory() as temporary_directory:
            temporary_path = Path(temporary_directory)
            environment = os.environ | {
                "ORCASLICER_BIN": "/definitely/missing/orca"
            }

            absent_output = temporary_path / "absent.gcode.3mf"
            absent_result = self.run_builder(absent_output, environment)
            self.assertNotEqual(absent_result.returncode, 0)
            self.assertIn("OrcaSlicer", absent_result.stderr)
            self.assertIn(
                "https://github.com/OrcaSlicer/OrcaSlicer/releases",
                absent_result.stderr,
            )
            self.assertFalse(absent_output.exists())

            existing_output = temporary_path / "existing.gcode.3mf"
            sentinel = b"pre-existing release artifact\x00\xff"
            existing_output.write_bytes(sentinel)
            existing_result = self.run_builder(existing_output, environment)
            self.assertNotEqual(existing_result.returncode, 0)
            self.assertEqual(existing_output.read_bytes(), sentinel)

    def test_missing_python3_preserves_destination(self):
        with tempfile.TemporaryDirectory() as temporary_directory:
            output = Path(temporary_directory) / "release.gcode.3mf"
            sentinel = b"known-good release\x00\xff"
            output.write_bytes(sentinel)
            environment = os.environ | {
                "PYTHON_BIN": "/definitely/missing/python3",
                "ORCASLICER_BIN": "/definitely/missing/orca",
            }

            result = self.run_builder(output, environment)

            self.assertNotEqual(result.returncode, 0)
            self.assertIn("Python 3", result.stderr)
            self.assertIn("https://www.python.org/downloads/", result.stderr)
            self.assertEqual(output.read_bytes(), sentinel)

    def test_rejects_orcaslicer_before_2_4_without_touching_destination(self):
        with tempfile.TemporaryDirectory() as temporary_directory:
            temporary_path = Path(temporary_directory)
            old_orca = temporary_path / "orca-2.3"
            self.make_executable(
                old_orca,
                "#!/usr/bin/env sh\n"
                "[ \"${1-}\" = --help ] || exit 70\n"
                "printf 'OrcaSlicer-2.3.9:\\n'\n",
            )
            openscad = temporary_path / "openscad"
            self.make_executable(openscad, "#!/usr/bin/env sh\nexit 0\n")

            output = temporary_path / "release.gcode.3mf"
            sentinel = b"keep the previous sliced release"
            output.write_bytes(sentinel)
            environment = os.environ | {
                "ORCASLICER_BIN": str(old_orca),
                "OPENSCAD_BIN": str(openscad),
            }

            result = self.run_builder(output, environment)

            self.assertNotEqual(result.returncode, 0)
            self.assertIn("OrcaSlicer", result.stderr)
            self.assertIn("2.4", result.stderr)
            self.assertIn(
                "https://github.com/OrcaSlicer/OrcaSlicer/releases",
                result.stderr,
            )
            self.assertEqual(output.read_bytes(), sentinel)

    def test_builds_four_object_slice_from_fresh_stls(self):
        with tempfile.TemporaryDirectory() as temporary_directory:
            temporary_path = Path(temporary_directory)
            openscad_arguments = temporary_path / "openscad-arguments.txt"
            orca_arguments = temporary_path / "orca-arguments.txt"

            openscad = temporary_path / "headless-openscad"
            self.make_executable(
                openscad,
                "#!/usr/bin/env python3\n"
                "import os, pathlib, sys\n"
                "args = sys.argv[1:]\n"
                "capture = pathlib.Path(os.environ['OPENSCAD_ARGS_FILE'])\n"
                "with capture.open('a', encoding='utf-8') as stream:\n"
                "    stream.write('\\n'.join(args) + '\\n')\n"
                "output = pathlib.Path(args[args.index('-o') + 1])\n"
                "output.write_bytes(b'fresh binary stl')\n",
            )
            orca = temporary_path / "headless-orca"
            self.make_executable(
                orca,
                "#!/usr/bin/env python3\n"
                "import json, os, pathlib, shutil, sys\n"
                "args = sys.argv[1:]\n"
                "if args == ['--help']:\n"
                "    print('OrcaSlicer-2.4.2:')\n"
                "    raise SystemExit(0)\n"
                "pathlib.Path(os.environ['ORCA_ARGS_FILE']).write_text(\n"
                "    '\\n'.join(args) + '\\n', encoding='utf-8'\n"
                ")\n"
                "output_directory = pathlib.Path(\n"
                "    args[args.index('--outputdir') + 1]\n"
                ")\n"
                "archive_name = args[args.index('--export-3mf') + 1]\n"
                "shutil.copy2(os.environ['P1S_FIXTURE'], output_directory / archive_name)\n"
                "(output_directory / 'result.json').write_text(\n"
                "    json.dumps({'return_code': 0}), encoding='utf-8'\n"
                ")\n",
            )

            output = temporary_path / "release.gcode.3mf"
            environment = os.environ | {
                "OPENSCAD_BIN": str(openscad),
                "ORCASLICER_BIN": str(orca),
                "OPENSCAD_ARGS_FILE": str(openscad_arguments),
                "ORCA_ARGS_FILE": str(orca_arguments),
                "P1S_FIXTURE": str(P1S_FIXTURE),
                "PYTHON_BIN": sys.executable,
            }
            environment.pop("DISPLAY", None)
            environment.pop("WAYLAND_DISPLAY", None)

            result = self.run_builder(output, environment)

            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertEqual(output.read_bytes(), P1S_FIXTURE.read_bytes())

            openscad_args = openscad_arguments.read_text(encoding="utf-8")
            self.assertEqual(openscad_args.count("part=\"main_print\""), 1)
            self.assertEqual(openscad_args.count("part=\"cap_print\""), 1)

            orca_args = orca_arguments.read_text(encoding="utf-8").splitlines()
            self.assertEqual(orca_args[orca_args.index("--arrange") + 1], "1")
            self.assertIn("--ensure-on-bed", orca_args)
            self.assertEqual(orca_args[orca_args.index("--slice") + 1], "0")
            self.assertIn("--export-slicedata", orca_args)
            self.assertEqual(
                orca_args[orca_args.index("--load-settings") + 1],
                f"{ROOT / 'profiles/orca/p1s-0.4-machine.json'};"
                f"{ROOT / 'profiles/orca/bracket-strength.json'}",
            )
            self.assertEqual(
                orca_args[orca_args.index("--load-filaments") + 1],
                str(ROOT / "profiles/orca/pla-basic.json"),
            )
            model_inputs = orca_args[-4:]
            self.assertEqual(
                [Path(model).name for model in model_inputs],
                ["main_print.stl", "main_print.stl", "cap_print.stl", "cap_print.stl"],
            )
            self.assertEqual(model_inputs[0], model_inputs[1])
            self.assertEqual(model_inputs[2], model_inputs[3])

    def test_nominal_orca_success_with_malformed_archive_preserves_destination(self):
        with tempfile.TemporaryDirectory() as temporary_directory:
            temporary_path = Path(temporary_directory)
            openscad = temporary_path / "openscad"
            self.make_executable(
                openscad,
                "#!/usr/bin/env python3\n"
                "import pathlib, sys\n"
                "args = sys.argv[1:]\n"
                "pathlib.Path(args[args.index('-o') + 1]).write_bytes(b'stl')\n",
            )
            orca = temporary_path / "orca"
            self.make_executable(
                orca,
                "#!/usr/bin/env python3\n"
                "import json, os, pathlib, shutil, sys\n"
                "args = sys.argv[1:]\n"
                "if args == ['--help']:\n"
                "    print('OrcaSlicer-2.4.2:')\n"
                "    raise SystemExit(0)\n"
                "output_directory = pathlib.Path(args[args.index('--outputdir') + 1])\n"
                "archive_name = args[args.index('--export-3mf') + 1]\n"
                "(output_directory / archive_name).write_bytes(b'nonempty malformed ZIP')\n"
                "(output_directory / 'result.json').write_text(\n"
                "    json.dumps({'return_code': 0}), encoding='utf-8'\n"
                ")\n",
            )
            output = temporary_path / "release.gcode.3mf"
            sentinel = b"known-good release\x00\xff"
            output.write_bytes(sentinel)
            environment = os.environ | {
                "OPENSCAD_BIN": str(openscad),
                "ORCASLICER_BIN": str(orca),
                "PYTHON_BIN": sys.executable,
            }

            result = self.run_builder(output, environment)

            self.assertNotEqual(result.returncode, 0)
            self.assertIn("ZIP", result.stderr)
            self.assertEqual(output.read_bytes(), sentinel)

    def test_nominal_orca_success_with_incomplete_archive_preserves_destination(self):
        with tempfile.TemporaryDirectory() as temporary_directory:
            temporary_path = Path(temporary_directory)
            openscad = temporary_path / "openscad"
            self.make_executable(
                openscad,
                "#!/usr/bin/env python3\n"
                "import pathlib, sys\n"
                "args = sys.argv[1:]\n"
                "pathlib.Path(args[args.index('-o') + 1]).write_bytes(b'stl')\n",
            )
            orca = temporary_path / "orca"
            self.make_executable(
                orca,
                "#!/usr/bin/env python3\n"
                "import json, pathlib, sys, zipfile\n"
                "args = sys.argv[1:]\n"
                "if args == ['--help']:\n"
                "    print('OrcaSlicer-2.4.2:')\n"
                "    raise SystemExit(0)\n"
                "output_directory = pathlib.Path(args[args.index('--outputdir') + 1])\n"
                "archive_name = args[args.index('--export-3mf') + 1]\n"
                "with zipfile.ZipFile(output_directory / archive_name, 'w') as archive:\n"
                "    archive.writestr('3D/3dmodel.model', '<model/>')\n"
                "(output_directory / 'result.json').write_text(\n"
                "    json.dumps({'return_code': 0}), encoding='utf-8'\n"
                ")\n",
            )
            output = temporary_path / "release.gcode.3mf"
            sentinel = b"known-good release\x00\xff"
            output.write_bytes(sentinel)
            environment = os.environ | {
                "OPENSCAD_BIN": str(openscad),
                "ORCASLICER_BIN": str(orca),
                "PYTHON_BIN": sys.executable,
            }

            result = self.run_builder(output, environment)

            self.assertNotEqual(result.returncode, 0)
            self.assertIn("missing", result.stderr.lower())
            self.assertEqual(output.read_bytes(), sentinel)

    def test_main_as_cap_substitution_preserves_destination(self):
        with tempfile.TemporaryDirectory() as temporary_directory:
            temporary_path = Path(temporary_directory)
            invalid_archive = temporary_path / "main-as-cap.gcode.3mf"
            shutil.copy2(P1S_FIXTURE, invalid_archive)
            with zipfile.ZipFile(invalid_archive) as source:
                main_mesh = source.read("3D/Objects/main_print.stl_1.model")
            self.rewrite_archive(
                invalid_archive,
                {
                    "3D/Objects/cap_print.stl_3.model": main_mesh,
                    "3D/Objects/cap_print.stl_4.model": main_mesh,
                },
            )

            openscad = temporary_path / "openscad"
            self.make_executable(
                openscad,
                "#!/usr/bin/env python3\n"
                "import pathlib, sys\n"
                "args = sys.argv[1:]\n"
                "pathlib.Path(args[args.index('-o') + 1]).write_bytes(b'stl')\n",
            )
            orca = temporary_path / "orca"
            self.make_fixture_orca(orca)
            output = temporary_path / "release.gcode.3mf"
            sentinel = b"known-good release\x00\xff"
            output.write_bytes(sentinel)
            environment = os.environ | {
                "INVALID_P1S_FIXTURE": str(invalid_archive),
                "OPENSCAD_BIN": str(openscad),
                "ORCASLICER_BIN": str(orca),
                "PYTHON_BIN": sys.executable,
            }

            result = self.run_builder(output, environment)

            self.assertNotEqual(result.returncode, 0)
            self.assertIn("cap", result.stderr.lower())
            self.assertEqual(output.read_bytes(), sentinel)

    def test_comment_only_gcode_preserves_destination(self):
        with tempfile.TemporaryDirectory() as temporary_directory:
            temporary_path = Path(temporary_directory)
            invalid_archive = temporary_path / "comment-only.gcode.3mf"
            shutil.copy2(P1S_FIXTURE, invalid_archive)
            gcode = b"; no printable toolpaths\n"
            self.rewrite_archive(
                invalid_archive,
                {
                    "Metadata/plate_1.gcode": gcode,
                    "Metadata/plate_1.gcode.md5": hashlib.md5(gcode).hexdigest(),
                },
            )

            openscad = temporary_path / "openscad"
            self.make_executable(
                openscad,
                "#!/usr/bin/env python3\n"
                "import pathlib, sys\n"
                "args = sys.argv[1:]\n"
                "pathlib.Path(args[args.index('-o') + 1]).write_bytes(b'stl')\n",
            )
            orca = temporary_path / "orca"
            self.make_fixture_orca(orca)
            output = temporary_path / "release.gcode.3mf"
            sentinel = b"known-good release\x00\xff"
            output.write_bytes(sentinel)
            environment = os.environ | {
                "INVALID_P1S_FIXTURE": str(invalid_archive),
                "OPENSCAD_BIN": str(openscad),
                "ORCASLICER_BIN": str(orca),
                "PYTHON_BIN": sys.executable,
            }

            result = self.run_builder(output, environment)

            self.assertNotEqual(result.returncode, 0)
            self.assertIn("layer", result.stderr.lower())
            self.assertEqual(output.read_bytes(), sentinel)

    def test_result_json_failure_preserves_destination(self):
        with tempfile.TemporaryDirectory() as temporary_directory:
            temporary_path = Path(temporary_directory)
            openscad = temporary_path / "openscad"
            self.make_executable(
                openscad,
                "#!/usr/bin/env python3\n"
                "import pathlib, sys\n"
                "args = sys.argv[1:]\n"
                "pathlib.Path(args[args.index('-o') + 1]).write_bytes(b'stl')\n",
            )
            orca = temporary_path / "orca"
            self.make_executable(
                orca,
                "#!/usr/bin/env python3\n"
                "import json, os, pathlib, shutil, sys\n"
                "args = sys.argv[1:]\n"
                "if args == ['--help']:\n"
                "    print('OrcaSlicer-2.4.2:')\n"
                "    raise SystemExit(0)\n"
                "output_directory = pathlib.Path(\n"
                "    args[args.index('--outputdir') + 1]\n"
                ")\n"
                "archive_name = args[args.index('--export-3mf') + 1]\n"
                "(output_directory / archive_name).write_bytes(b'invalid slice')\n"
                "(output_directory / 'result.json').write_text(\n"
                "    json.dumps({'return_code': -17}), encoding='utf-8'\n"
                ")\n",
            )
            output = temporary_path / "release.gcode.3mf"
            sentinel = b"known-good release"
            output.write_bytes(sentinel)
            environment = os.environ | {
                "OPENSCAD_BIN": str(openscad),
                "ORCASLICER_BIN": str(orca),
            }

            result = self.run_builder(output, environment)

            self.assertNotEqual(result.returncode, 0)
            self.assertIn("result.json", result.stderr)
            self.assertEqual(output.read_bytes(), sentinel)

    def test_empty_archive_preserves_destination(self):
        with tempfile.TemporaryDirectory() as temporary_directory:
            temporary_path = Path(temporary_directory)
            openscad = temporary_path / "openscad"
            self.make_executable(
                openscad,
                "#!/usr/bin/env python3\n"
                "import pathlib, sys\n"
                "args = sys.argv[1:]\n"
                "pathlib.Path(args[args.index('-o') + 1]).write_bytes(b'stl')\n",
            )
            orca = temporary_path / "orca"
            self.make_executable(
                orca,
                "#!/usr/bin/env python3\n"
                "import json, pathlib, sys\n"
                "args = sys.argv[1:]\n"
                "if args == ['--help']:\n"
                "    print('OrcaSlicer-2.4.2:')\n"
                "    raise SystemExit(0)\n"
                "output_directory = pathlib.Path(\n"
                "    args[args.index('--outputdir') + 1]\n"
                ")\n"
                "archive_name = args[args.index('--export-3mf') + 1]\n"
                "(output_directory / archive_name).touch()\n"
                "(output_directory / 'result.json').write_text(\n"
                "    json.dumps({'return_code': 0}), encoding='utf-8'\n"
                ")\n",
            )
            output = temporary_path / "release.gcode.3mf"
            sentinel = b"known-good release"
            output.write_bytes(sentinel)
            environment = os.environ | {
                "OPENSCAD_BIN": str(openscad),
                "ORCASLICER_BIN": str(orca),
            }

            result = self.run_builder(output, environment)

            self.assertNotEqual(result.returncode, 0)
            self.assertIn("nonempty", result.stderr)
            self.assertEqual(output.read_bytes(), sentinel)

    def test_version_probe_runs_in_private_directory(self):
        with tempfile.TemporaryDirectory() as temporary_directory:
            temporary_path = Path(temporary_directory)
            version_working_directory = temporary_path / "version-cwd.txt"
            orca = temporary_path / "orca"
            self.make_executable(
                orca,
                "#!/usr/bin/env python3\n"
                "import os, pathlib, sys\n"
                "if sys.argv[1:] == ['--help']:\n"
                "    pathlib.Path(os.environ['VERSION_CWD_FILE']).write_text(\n"
                "        str(pathlib.Path.cwd()), encoding='utf-8'\n"
                "    )\n"
                "    print('OrcaSlicer-2.4.2:')\n"
                "    raise SystemExit(0)\n"
                "raise SystemExit(71)\n",
            )
            openscad = temporary_path / "openscad"
            self.make_executable(openscad, "#!/usr/bin/env sh\nexit 72\n")
            environment = os.environ | {
                "OPENSCAD_BIN": str(openscad),
                "ORCASLICER_BIN": str(orca),
                "VERSION_CWD_FILE": str(version_working_directory),
            }

            result = self.run_builder(
                temporary_path / "release.gcode.3mf", environment
            )

            self.assertNotEqual(result.returncode, 0)
            probe_directory = Path(
                version_working_directory.read_text(encoding="utf-8")
            )
            self.assertNotEqual(probe_directory, ROOT)
            self.assertTrue(probe_directory.name.startswith("wardrobe-rail-holder."))

    def test_relative_orcaslicer_override_survives_private_version_probe(self):
        with tempfile.TemporaryDirectory(dir=Path.cwd()) as temporary_directory:
            temporary_path = Path(temporary_directory)
            openscad = temporary_path / "openscad"
            self.make_executable(
                openscad,
                "#!/usr/bin/env python3\n"
                "import pathlib, sys\n"
                "args = sys.argv[1:]\n"
                "pathlib.Path(args[args.index('-o') + 1]).write_bytes(b'stl')\n",
            )
            orca = temporary_path / "relative-orca"
            self.make_executable(
                orca,
                "#!/usr/bin/env python3\n"
                "import json, os, pathlib, shutil, sys\n"
                "args = sys.argv[1:]\n"
                "if args == ['--help']:\n"
                "    print('OrcaSlicer-2.4.2:')\n"
                "    raise SystemExit(0)\n"
                "output_directory = pathlib.Path(\n"
                "    args[args.index('--outputdir') + 1]\n"
                ")\n"
                "archive_name = args[args.index('--export-3mf') + 1]\n"
                "shutil.copy2(os.environ['P1S_FIXTURE'], output_directory / archive_name)\n"
                "(output_directory / 'result.json').write_text(\n"
                "    json.dumps({'return_code': 0}), encoding='utf-8'\n"
                ")\n",
            )
            relative_orca = os.path.relpath(orca, Path.cwd())
            self.assertFalse(Path(relative_orca).is_absolute())
            output = temporary_path / "release.gcode.3mf"
            environment = os.environ | {
                "OPENSCAD_BIN": str(openscad),
                "ORCASLICER_BIN": relative_orca,
                "P1S_FIXTURE": str(P1S_FIXTURE),
                "PYTHON_BIN": sys.executable,
            }

            result = self.run_builder(output, environment)

            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertEqual(output.read_bytes(), P1S_FIXTURE.read_bytes())

    def test_slice_must_write_a_fresh_result_json(self):
        with tempfile.TemporaryDirectory() as temporary_directory:
            temporary_path = Path(temporary_directory)
            openscad = temporary_path / "openscad"
            self.make_executable(
                openscad,
                "#!/usr/bin/env python3\n"
                "import pathlib, sys\n"
                "args = sys.argv[1:]\n"
                "pathlib.Path(args[args.index('-o') + 1]).write_bytes(b'stl')\n",
            )
            orca = temporary_path / "orca"
            self.make_executable(
                orca,
                "#!/usr/bin/env python3\n"
                "import json, pathlib, sys\n"
                "args = sys.argv[1:]\n"
                "if args == ['--help']:\n"
                "    pathlib.Path('result.json').write_text(\n"
                "        json.dumps({'return_code': 0}), encoding='utf-8'\n"
                "    )\n"
                "    print('OrcaSlicer-2.4.2:')\n"
                "    raise SystemExit(0)\n"
                "output_directory = pathlib.Path(\n"
                "    args[args.index('--outputdir') + 1]\n"
                ")\n"
                "archive_name = args[args.index('--export-3mf') + 1]\n"
                "(output_directory / archive_name).write_bytes(b'slice')\n",
            )
            output = temporary_path / "release.gcode.3mf"
            sentinel = b"known-good release"
            output.write_bytes(sentinel)
            environment = os.environ | {
                "OPENSCAD_BIN": str(openscad),
                "ORCASLICER_BIN": str(orca),
            }

            result = self.run_builder(output, environment)

            self.assertNotEqual(result.returncode, 0)
            self.assertIn("result.json", result.stderr)
            self.assertEqual(output.read_bytes(), sentinel)


class RealOrcaSmokeTests(unittest.TestCase):
    def locate_orca(self):
        override = os.environ.get("ORCASLICER_BIN")
        if override:
            return override if os.access(override, os.X_OK) else None
        for candidate in ("orca-slicer", "orcaslicer", "OrcaSlicer"):
            located = shutil.which(candidate)
            if located:
                return located
        return None

    def test_real_orca_builds_valid_p1s_archive_without_display(self):
        orca = self.locate_orca()
        if orca is None:
            self.skipTest(
                "OrcaSlicer unavailable via ORCASLICER_BIN or supported PATH names"
            )
        if shutil.which("openscad") is None and not os.environ.get("OPENSCAD_BIN"):
            self.skipTest("OpenSCAD unavailable for the real Orca smoke test")

        with tempfile.TemporaryDirectory() as temporary_directory:
            output = Path(temporary_directory) / "smoke.gcode.3mf"
            environment = os.environ | {
                "ORCASLICER_BIN": orca,
                "PYTHON_BIN": sys.executable,
            }
            environment.pop("DISPLAY", None)
            environment.pop("WAYLAND_DISPLAY", None)

            build = subprocess.run(
                [str(BUILD_P1S), "--output", str(output)],
                text=True,
                capture_output=True,
                env=environment,
                timeout=900,
            )
            self.assertEqual(build.returncode, 0, build.stderr)

            validation = subprocess.run(
                [sys.executable, str(VALIDATOR), "p1s", str(output)],
                text=True,
                capture_output=True,
                timeout=120,
            )
            self.assertEqual(validation.returncode, 0, validation.stderr)


if __name__ == "__main__":
    unittest.main(verbosity=2)
