import os
import shutil
import struct
import subprocess
import tempfile
import unittest
import xml.etree.ElementTree as ET
import zipfile
from collections import defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
BUILD_MODELS = ROOT / "scripts" / "build-models.sh"

EXPECTED = {
    "wardrobe_rail_bracket_main.stl": ((63.5, 75.0, 30.0), 1),
    "wardrobe_rail_bracket_cap.stl": ((63.5, 24.0, 15.7), 1),
    "wardrobe_rail_bracket_main.3mf": ((63.5, 75.0, 30.0), 1),
    "wardrobe_rail_bracket_cap.3mf": ((63.5, 24.0, 15.7), 1),
}

RELEASE_FILENAMES = set(EXPECTED) | {"wardrobe_rail_bracket_complete.3mf"}


def binary_stl_triangles(path: Path):
    data = path.read_bytes()
    if len(data) < 84:
        raise AssertionError(f"STL is too small: {len(data)} bytes")

    triangle_count = struct.unpack_from("<I", data, 80)[0]
    if 84 + triangle_count * 50 != len(data):
        raise AssertionError("Expected a binary STL generated by OpenSCAD")

    return [
        [
            struct.unpack_from("<fff", data, 84 + triangle * 50 + 12 + vertex * 12)
            for vertex in range(3)
        ]
        for triangle in range(triangle_count)
    ]


def model_triangles_from_3mf(path: Path):
    with zipfile.ZipFile(path) as archive:
        model = ET.fromstring(archive.read("3D/3dmodel.model"))

    namespace = "{http://schemas.microsoft.com/3dmanufacturing/core/2015/02}"
    vertices = [
        tuple(float(vertex.attrib[axis]) for axis in ("x", "y", "z"))
        for vertex in model.findall(f".//{namespace}vertex")
    ]
    return [
        [
            vertices[int(triangle.attrib[corner])]
            for corner in ("v1", "v2", "v3")
        ]
        for triangle in model.findall(f".//{namespace}triangle")
    ]


def envelope_and_components(triangles):
    coordinates = list(zip(*(vertex for triangle in triangles for vertex in triangle)))
    lower = tuple(min(axis) for axis in coordinates)
    upper = tuple(max(axis) for axis in coordinates)

    edge_triangles = defaultdict(list)
    for index, triangle in enumerate(triangles):
        for start, end in ((0, 1), (1, 2), (2, 0)):
            edge_triangles[tuple(sorted((triangle[start], triangle[end])))].append(index)

    neighbours = defaultdict(set)
    for adjacent_triangles in edge_triangles.values():
        for triangle in adjacent_triangles:
            neighbours[triangle].update(
                other for other in adjacent_triangles if other != triangle
            )

    unseen = set(range(len(triangles)))
    components = 0
    while unseen:
        components += 1
        pending = [unseen.pop()]
        while pending:
            adjacent = neighbours[pending.pop()] & unseen
            unseen.difference_update(adjacent)
            pending.extend(adjacent)

    return tuple(round(high - low, 1) for low, high in zip(lower, upper)), components, lower


class ReleaseModelBuildTests(unittest.TestCase):
    def test_repository_has_no_obsolete_root_model_exports(self):
        for filename in ("wardrobe_rail_bracket.3mf", "wardrobe_rail_bracket.stl"):
            with self.subTest(filename=filename):
                self.assertFalse(
                    (ROOT / filename).exists(),
                    f"obsolete root model export found: {filename}",
                )

    def run_builder(self, output_directory: Path, environment=None):
        self.assertTrue(BUILD_MODELS.is_file(), "scripts/build-models.sh is missing")
        return subprocess.run(
            [str(BUILD_MODELS), "--output-dir", str(output_directory)],
            text=True,
            capture_output=True,
            env=environment,
        )

    def test_builds_portable_models_with_expected_print_envelopes(self):
        with tempfile.TemporaryDirectory() as temporary_directory:
            output_directory = Path(temporary_directory)
            result = self.run_builder(output_directory)

            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertEqual(
                {path.name for path in output_directory.iterdir()}, RELEASE_FILENAMES
            )

            for filename, (expected_size, expected_components) in EXPECTED.items():
                with self.subTest(filename=filename):
                    output = output_directory / filename
                    triangles = (
                        binary_stl_triangles(output)
                        if output.suffix == ".stl"
                        else model_triangles_from_3mf(output)
                    )
                    size, components, lower = envelope_and_components(triangles)
                    self.assertEqual(size, expected_size)
                    self.assertEqual(components, expected_components)
                    self.assertGreaterEqual(lower[2], 0.0)

            for filename in (
                "wardrobe_rail_bracket_main.3mf",
                "wardrobe_rail_bracket_cap.3mf",
                "wardrobe_rail_bracket_complete.3mf",
            ):
                with self.subTest(filename=filename, contract="neutral archive"):
                    self.assert_clean_3mf(output_directory / filename)

    def test_complete_model_is_neutral_two_volume_print_layout(self):
        with tempfile.TemporaryDirectory() as temporary_directory:
            output_directory = Path(temporary_directory)
            result = self.run_builder(output_directory)

            self.assertEqual(result.returncode, 0, result.stderr)
            complete = output_directory / "wardrobe_rail_bracket_complete.3mf"
            triangles = model_triangles_from_3mf(complete)
            _, components, lower = envelope_and_components(triangles)
            self.assertEqual(components, 2)
            self.assertGreaterEqual(lower[2], 0.0)

            self.assert_clean_3mf(complete)

    def test_builds_with_no_display_server(self):
        openscad = shutil.which("openscad")
        self.assertIsNotNone(openscad, "OpenSCAD CLI is not installed")

        with tempfile.TemporaryDirectory() as temporary_directory:
            temporary_path = Path(temporary_directory)
            wrapper = temporary_path / "headless-openscad"
            wrapper.write_text(
                "#!/usr/bin/env sh\n"
                "[ -z \"${DISPLAY-}\" ] || exit 61\n"
                "[ -z \"${WAYLAND_DISPLAY-}\" ] || exit 62\n"
                "[ \"${QT_QPA_PLATFORM-}\" = offscreen ] || exit 63\n"
                f"exec {openscad} \"$@\"\n",
                encoding="utf-8",
            )
            wrapper.chmod(0o755)
            environment = os.environ | {"OPENSCAD_BIN": str(wrapper)}
            environment.pop("DISPLAY", None)
            environment.pop("WAYLAND_DISPLAY", None)
            environment.pop("QT_QPA_PLATFORM", None)

            result = self.run_builder(temporary_path / "models", environment)

            self.assertEqual(result.returncode, 0, result.stderr)

    def test_missing_openscad_leaves_output_directory_unchanged(self):
        with tempfile.TemporaryDirectory() as temporary_directory:
            output_directory = Path(temporary_directory)
            sentinel = output_directory / "keep.txt"
            sentinel.write_text("do not touch", encoding="utf-8")
            environment = os.environ | {"OPENSCAD_BIN": "/definitely/missing/openscad"}
            result = self.run_builder(output_directory, environment)

            self.assertNotEqual(result.returncode, 0)
            self.assertIn("OpenSCAD", result.stderr)
            self.assertIn("https://openscad.org/downloads.html", result.stderr)
            self.assertEqual(sentinel.read_text(encoding="utf-8"), "do not touch")
            self.assertFalse(RELEASE_FILENAMES & {path.name for path in output_directory.iterdir()})

    def assert_clean_3mf(self, output: Path):
        with zipfile.ZipFile(output) as archive:
            names = archive.namelist()
        self.assertFalse(any(name.endswith(".gcode") for name in names))
        self.assertFalse(
            {
                "Metadata/project_settings.config",
                "Metadata/model_settings.config",
                "Metadata/slice_info.config",
            }
            & set(names)
        )


if __name__ == "__main__":
    unittest.main(verbosity=2)
