import shutil
import struct
import subprocess
import tempfile
import unittest
from collections import Counter, defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MODEL = ROOT / "wardrobe_rail_bracket.scad"
OPENSCAD = shutil.which("openscad")


def stl_bounds(path: Path):
    """Return ((min_x, min_y, min_z), (max_x, max_y, max_z), triangles)."""
    data = path.read_bytes()
    if len(data) < 84:
        raise AssertionError(f"STL is too small: {len(data)} bytes")

    triangle_count = struct.unpack_from("<I", data, 80)[0]
    expected_size = 84 + triangle_count * 50
    if expected_size != len(data):
        raise AssertionError("Expected a binary STL generated by OpenSCAD")

    coordinates = [[], [], []]
    for triangle in range(triangle_count):
        offset = 84 + triangle * 50 + 12
        for vertex in range(3):
            values = struct.unpack_from("<fff", data, offset + vertex * 12)
            for axis, value in enumerate(values):
                coordinates[axis].append(value)

    lower = tuple(min(axis) for axis in coordinates)
    upper = tuple(max(axis) for axis in coordinates)
    return lower, upper, triangle_count


def stl_topology(path: Path):
    """Return connected component and invalid edge counts for a binary STL."""
    data = path.read_bytes()
    triangle_count = struct.unpack_from("<I", data, 80)[0]
    edge_counts = Counter()
    edge_triangles = defaultdict(list)

    for triangle in range(triangle_count):
        offset = 84 + triangle * 50 + 12
        vertices = [
            struct.unpack_from("<fff", data, offset + vertex * 12)
            for vertex in range(3)
        ]
        for start, end in ((0, 1), (1, 2), (2, 0)):
            edge = tuple(sorted((vertices[start], vertices[end])))
            edge_counts[edge] += 1
            edge_triangles[edge].append(triangle)

    neighbours = defaultdict(set)
    for triangles in edge_triangles.values():
        for triangle in triangles:
            neighbours[triangle].update(other for other in triangles if other != triangle)

    unseen = set(range(triangle_count))
    components = 0
    while unseen:
        components += 1
        pending = [unseen.pop()]
        while pending:
            triangle = pending.pop()
            adjacent = neighbours[triangle] & unseen
            unseen.difference_update(adjacent)
            pending.extend(adjacent)

    invalid_edges = sum(count != 2 for count in edge_counts.values())
    return components, invalid_edges


@unittest.skipUnless(OPENSCAD, "OpenSCAD CLI is not installed")
class OpenScadRenderTests(unittest.TestCase):
    def render(self, output_mode: str, *definitions: str):
        temporary_directory = tempfile.TemporaryDirectory()
        self.addCleanup(temporary_directory.cleanup)
        output = Path(temporary_directory.name) / f"{output_mode}.stl"
        command = [
            OPENSCAD,
            "--export-format",
            "binstl",
            "-o",
            str(output),
            "-D",
            f'part="{output_mode}"',
        ]
        for definition in definitions:
            command.extend(["-D", definition])
        command.append(str(MODEL))
        result = subprocess.run(command, text=True, capture_output=True)
        return result, output

    def assert_probe_does_not_intersect(self, model_output, probe_body, message):
        probe = model_output.parent / "clearance-probe.scad"
        obstruction = model_output.parent / "clearance-probe.stl"
        probe.write_text(
            "intersection() {\n"
            f'  import("{model_output.as_posix()}");\n'
            f"  {probe_body}\n"
            "}\n",
            encoding="utf-8",
        )
        result = subprocess.run(
            [
                OPENSCAD,
                "--export-format",
                "binstl",
                "-o",
                str(obstruction),
                str(probe),
            ],
            text=True,
            capture_output=True,
        )
        self.assertNotEqual(result.returncode, 0, message)
        self.assertIn("Current top level object is empty", result.stderr)

    def test_all_output_modes_render_as_nonempty_solids(self):
        expected_components = {"assembly": 2, "main": 1, "cap": 1, "print": 2}
        for mode in ("assembly", "main", "cap", "print"):
            with self.subTest(mode=mode):
                result, output = self.render(mode)
                self.assertEqual(result.returncode, 0, result.stderr)
                lower, upper, triangle_count = stl_bounds(output)
                self.assertGreater(triangle_count, 100)
                self.assertTrue(all(high > low for low, high in zip(lower, upper)))
                components, invalid_edges = stl_topology(output)
                self.assertEqual(components, expected_components[mode])
                self.assertEqual(invalid_edges, 0, "STL contains non-manifold edges")

    def test_assembly_has_planned_overall_envelope(self):
        result, output = self.render("assembly")
        self.assertEqual(result.returncode, 0, result.stderr)
        lower, upper, _ = stl_bounds(output)
        size = tuple(round(high - low, 1) for low, high in zip(lower, upper))
        self.assertEqual(size[0:2], (63.5, 75.0))
        self.assertGreaterEqual(size[2], 45.5)
        self.assertLessEqual(size[2], 47.0)

    def test_individual_print_modes_are_manifold_and_on_the_build_plate(self):
        expected_sizes = {
            "main_print": (63.5, 75.0, 30.0),
            "cap_print": (63.5, 24.0, 15.7),
        }
        for mode, expected_size in expected_sizes.items():
            with self.subTest(mode=mode):
                result, output = self.render(mode)
                self.assertEqual(result.returncode, 0, result.stderr)
                lower, upper, _ = stl_bounds(output)
                self.assertEqual(round(lower[2], 3), 0.0)
                size = tuple(round(high - low, 1) for low, high in zip(lower, upper))
                self.assertEqual(size, expected_size)
                components, invalid_edges = stl_topology(output)
                self.assertEqual(components, 1)
                self.assertEqual(invalid_edges, 0)

    def test_custom_rail_dimensions_change_clamp_envelope(self):
        default_result, default_output = self.render("cap")
        self.assertEqual(default_result.returncode, 0, default_result.stderr)
        _, default_upper, _ = stl_bounds(default_output)

        custom_result, custom_output = self.render(
            "cap", "rail_width=18", "rail_height=34", "rail_radius=8"
        )
        self.assertEqual(custom_result.returncode, 0, custom_result.stderr)
        _, custom_upper, _ = stl_bounds(custom_output)
        self.assertGreater(custom_upper[0], default_upper[0])

    def test_ceiling_screw_heads_have_an_unobstructed_path_from_below(self):
        result, main_output = self.render("main")
        self.assertEqual(result.returncode, 0, result.stderr)

        for screw_y in (-20, 20):
            with self.subTest(screw_y=screw_y):
                probe = main_output.parent / f"screw-access-{screw_y}.scad"
                obstruction = main_output.parent / f"screw-access-{screw_y}.stl"
                probe.write_text(
                    "intersection() {\n"
                    f'  import("{main_output.as_posix()}");\n'
                    f"  translate([0, {screw_y}, -50]) cylinder(h=42, d=8.5, $fn=32);\n"
                    "}\n",
                    encoding="utf-8",
                )
                probe_result = subprocess.run(
                    [
                        OPENSCAD,
                        "--export-format",
                        "binstl",
                        "-o",
                        str(obstruction),
                        str(probe),
                    ],
                    text=True,
                    capture_output=True,
                )
                self.assertNotEqual(
                    probe_result.returncode,
                    0,
                    "solid material obstructs the ceiling screw-head access path",
                )
                self.assertIn("Current top level object is empty", probe_result.stderr)

    def test_main_bolt_boss_has_continuous_print_support(self):
        result, main_output = self.render("main_print")
        self.assertEqual(result.returncode, 0, result.stderr)

        unsupported_probe = main_output.parent / "unsupported-boss-probe.scad"
        unsupported_output = main_output.parent / "unsupported-boss-probe.stl"
        unsupported_probe.write_text(
            "difference() {\n"
            "  translate([26.5, 0, 8]) cylinder(h=4, r=0.15, $fn=16);\n"
            f'  import("{main_output.as_posix()}");\n'
            "}\n",
            encoding="utf-8",
        )
        probe_result = subprocess.run(
            [
                OPENSCAD,
                "--export-format",
                "binstl",
                "-o",
                str(unsupported_output),
                str(unsupported_probe),
            ],
            text=True,
            capture_output=True,
        )
        self.assertNotEqual(
            probe_result.returncode,
            0,
            "the outer bolt boss begins as an unsupported cantilever",
        )
        self.assertIn("Current top level object is empty", probe_result.stderr)

    def test_m6_button_head_bolt_and_standard_nut_fit_the_voids(self):
        cap_result, cap_output = self.render("cap")
        self.assertEqual(cap_result.returncode, 0, cap_result.stderr)
        main_result, main_output = self.render("main")
        self.assertEqual(main_result.returncode, 0, main_result.stderr)

        for side in (-1, 1):
            bolt_x = side * 19.75
            with self.subTest(side=side, hardware="button-head bolt"):
                self.assert_probe_does_not_intersect(
                    cap_output,
                    "union() {"
                    f" translate([{bolt_x}, 0, -36.4]) cylinder(h=3.3, d=10.5, $fn=64);"
                    f" translate([{bolt_x}, 0, -33.1]) cylinder(h=12, d=6, $fn=64);"
                    " }",
                    "nominal M6 button-head hardware intersects the cap",
                )

            with self.subTest(side=side, hardware="standard hex nut"):
                self.assert_probe_does_not_intersect(
                    main_output,
                    "union() {"
                    f" translate([{bolt_x}, 0, -27.48]) cylinder(h=4.96, r=10/sqrt(3), $fn=6);"
                    f" translate([{bolt_x - 10 / 3 ** 0.5}, -12.98, -27.48])"
                    f" cube([{20 / 3 ** 0.5}, 12.96, 4.96]);"
                    " }",
                    "standard M6 nut cannot occupy or enter the captive pocket",
                )

    def test_bolt_length_must_fully_engage_the_captive_nut(self):
        result, _ = self.render("main", "clamp_bolt_length=10")
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("clamp bolt is too short to engage the captive nut", result.stderr)

    def test_invalid_rail_radius_is_rejected(self):
        result, _ = self.render("main", "rail_radius=8")
        self.assertNotEqual(result.returncode, 0)
        self.assertIn(
            "rail_radius must be at most half the smaller rail dimension",
            result.stderr,
        )

    def test_undersized_structural_parameters_are_rejected(self):
        cases = (
            ("wall_thickness=5.9", "wall_thickness must be at least 6 mm"),
            ("bolt_lug_radius=5", "bolt lug is too small around the bolt head"),
            ("bolt_x=17.8", "not enough material between socket and captive nut"),
            ("plate_thickness=-1", "plate dimensions must be positive"),
            ("clamp_depth=0", "clamp_depth must be positive"),
        )
        for definition, message in cases:
            with self.subTest(definition=definition):
                result, _ = self.render("main", definition)
                self.assertNotEqual(result.returncode, 0)
                self.assertIn(message, result.stderr)


class ModelContractTests(unittest.TestCase):
    def test_model_file_exists(self):
        self.assertTrue(MODEL.is_file(), "wardrobe_rail_bracket.scad is missing")


if __name__ == "__main__":
    unittest.main(verbosity=2)
